# Mermaid Diagram System Configuration

# Directory Settings
directories:
  base_dir: "."  # Relative to script location
  output_dir: "output"  # For generated files
  temp_dir: "temp"  # For temporary files

# Style Definitions
styles:
  # Core Processing styles
  core_processing:
    color: "#e6f3ff"
    classes:
      - core
      - dsl
      - recognition
      - modeling
      - generation

  # System Infrastructure styles
  system_infrastructure:
    color: "#e6ffe6"
    classes:
      - engine
      - plugins
      - processing
      - patterns

  # UI & Integration styles
  ui_integration:
    color: "#ffe6cc"
    classes:
      - interface
      - utils
      - persistence

  # System Support styles
  system_support:
    color: "#f2e6ff"
    classes:
      - testing
      - error_handling
      - logging

# Validation Rules
validation:
  syntax:
    require_graph_td: true
    check_balanced_quotes: true
    check_arrow_syntax: true
    allow_comments: true
    
  components:
    require_description: true
    name_pattern: "^[A-Za-z][A-Za-z0-9_]*$"
    max_name_length: 50
    
  dependencies:
    allow_circular: false
    max_depth: 10
    validate_components: true
    
  styles:
    require_defined_styles: true
    allow_custom_colors: false

# Error Handling
error_handling:
  strict_mode: true
  max_errors: 100
  stop_on_critical: true
  log_all_errors: true
  
  severity_levels:
    critical:
      - syntax_error
      - file_not_found
      - invalid_config
    warning:
      - undefined_style
      - potential_cycle
      - long_name
    info:
      - style_override
      - optional_field_missing

# Logging Configuration
logging:
  enabled: true
  level: "INFO"
  format: "[%(levelname)s] %(asctime)s - %(message)s"
  file: "mermaid_validator.log"
  rotate: true
  max_size: "10MB"
  backup_count: 5
  
  console:
    enabled: true
    color: true
    level: "INFO"
    
  file_logging:
    enabled: true
    level: "DEBUG"
    include_timestamp: true

# Report Generation
reporting:
  format: "rich"  # rich, plain, or json
  sections:
    - inputs
    - outputs
    - validations
    - errors
    - summary
  
  output_formats:
    - console
    - file
    - json
    
  summary_stats:
    include_timing: true
    show_memory_usage: true
    count_by_category: true

# Performance Settings
performance:
  parallel_processing: true
  max_workers: 4
  chunk_size: 1000
  cache_enabled: true
  cache_ttl: 3600  # seconds 